homepage:
  pattern: /
  defaults: { _controller: YrchBundle:Main:index }

localized_homepage:
  locales: { en: /en, fr: /fr}
  defaults: { _controller: YrchBundle:Category:show }
  requirements: { _method: "GET" }

category_show:
  locales: { en: /en/category/:id, fr: /fr/categorie/:id }
  defaults: { _controller: YrchBundle:Category:show }
  requirements: { id: "\d+", _method: "GET" }

site_show:
  locales: { en: /en/site/:id, fr: /fr/site/:id }
  defaults: { _controller: YrchBundle:Site:show }
  requirements: { id: "\d+", _method: "GET" }

site_new:
  locales: { en: /en/site/new, fr: /fr/site/nouveau }
  defaults: { _controller: YrchBundle:Site:new }
  requirements: { _method: "GET" }

site_create:
  locales: { en: /en/site/new, fr: /fr/site/nouveau }
  defaults: { _controller: YrchBundle:Site:create }
  requirements: { _method: "POST" }
