<?php

namespace Application\YrchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteTranslationRepository extends EntityRepository
{
}